### PR TITLE
Mitigate risky code parts

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 5 BUG
 - 1 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1006

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-el7/16/ : FAILURE in 7m 29s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/1/ : SUCCESS in 9s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by peter-plochan — APPROVED** [review]

**Comment by petr-klemsinsky** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 6 BUG
 - 1 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1006

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-el7/17/ : FAILURE in 5m 13s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/2/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/214/ : SUCCESS in 27s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/54/ : SUCCESS in 18s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1006

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-el7/18/ : SUCCESS in 10m 24s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/3/ : SUCCESS in 16s

**Pull request merged**
