### PR TITLE
Extend .gitignore to fix sonar exclusion

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new issues found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1073

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-extended/1/ : SUCCESS in 5m 42s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/4/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 20 BUG
 - 948 CODE_SMELL
 - 2 VULNERABILITY

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1073
The scan job will fail because a vulnerability has been found

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-extended/2/ : FAILURE in 6m 40s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/5/ : SUCCESS in 7s

**Pull request closed without merging**
