### PR TITLE
Exclude surefire/failsafe reports from dependency check

### PR DESCRIPTION
**Pull request by liry**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-java-check-extended-sonar-PR1075

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-sonarqube-scan-zuul-extended/3/ : SUCCESS in 8m 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-oss-check/6/ : SUCCESS in 11s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by peter-plochan — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/258/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/97/ : FAILURE in 2m 59s (non-voting)

**Pull request merged**
