### PR TITLE
Fix the wrongly refactored user listing cycle

### LINKED ISSUE #905: Infinite cycle in acceptance tests

### PR DESCRIPTION
**Pull request by jimirocks**
Resolves #905

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/142/ : FAILURE in 0s

**Comment by peter-plochan** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/143/ : FAILURE in 2s

**Pull request merged**
