### PR TITLE
Split SDK into model and service module

### LINKED ISSUE #697: Split the library in two modules: dtos and the rest
Pros:
* DTOs can be used  also in internal code easily
* Ability to separate evolution of dtos and services (i.e. upgrade of jackson vs. upgrade of spring)

### PR DESCRIPTION
**Pull request by jimirocks**
Resolves #697

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by To-da** [comment]
why gooddata-model have package com.gooddata.sdk* ?

**Comment by jimirocks** [comment]
@To-da my proposal is that all the SDK classes have `com.gooddata.sdk.*` package, probably `com.gooddata.sdk.model.*` for model and similar for the service...  but since the model and service in some cases have some common package private classes I didn't go so far yet.

**Comment by liry** [comment]
#697

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
FYI: packages changed + dependencies redistributed to particular modules

**Comment by jimirocks** [comment]
As @liry suggested, it might be a good idea to keep artifact `com.gooddata:gooddata-java` for publishing the service part?

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
FYI: modules renamed + squashed

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
👍

**Comment by liry** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/51/ : SUCCESS in 19s

**Pull request merged**
