### PR TITLE
Add authenticationModes to Account.java

### LINKED ISSUE #1056: Support authenticationModes property in Account.java
authenticationModes is supported when using JSON directly, but library does not have field.

### PR DESCRIPTION
**Pull request by cipous**
Fixes https://github.com/gooddata/gooddata-java/issues/1056

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by cipous** [comment]
fixes #1056

**Review by peter-plochan — APPROVED** [review]
LGTM 👍

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/242/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/81/ : SUCCESS in 57s (non-voting)

**Comment by liry** [comment]
@cipous Thank you for the contribution ;)

**Pull request merged**
