### PR TITLE
INFRA-176: Add sonar properties - configuration for sonarcloud

### PR DESCRIPTION
**Pull request by tomaso**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by sadam21** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/303/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul/1/ : SUCCESS in 1m 46s (non-voting)

**Pull request merged**
