### PR TITLE
Add workspace timezone setting

### PR DESCRIPTION
**Pull request by liry**
Implements #1049

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by jimirocks — APPROVED** [review]

**Comment by liry** [comment]
Only GET implemented so far. PUT should be added soon.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by liry** [comment]
@jimirocks now it's complete ;)

**Review by peter-plochan — APPROVED** [review]
LGTM 👍

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-java-merge-compliance-check/262/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-java-fossa-scanning-zuul-el7/101/ : SUCCESS in 55s (non-voting)

**Pull request merged**
